import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createExpertReplayStore,registerExpertReplayTool} from '../src/expert-replay-session.js';
test('frozen replay IDs cache, cap and changed binding fail closed',async()=>{const root=await mkdtemp(join(tmpdir(),'expert-replay-'));let count=0;const run=createExpertReplayStore(root,'a',async()=>({n:++count}),2);let tool:any;registerExpertReplayTool({registerTool:(t:any)=>tool=t},run);await tool.execute('t',{runIds:['one','two']});const cached:any=await run(['one','three','one']);assert.equal(count,2);assert.equal(cached[0].delivery,'cached-existing');assert.equal(cached[1].status,'limit-reached');await assert.rejects(createExpertReplayStore(root,'changed',async()=>null)(['one']),/binding changed/);});
test('failed replay is retained without another execution',async()=>{const root=await mkdtemp(join(tmpdir(),'expert-replay-'));let count=0;const run=createExpertReplayStore(root,'a',async()=>{count++;throw Error('original failure');});await run(['one']);const r:any=await run(['one']);assert.equal(count,1);assert.equal(r[0].status,'failed');});

import {agentTaskToolArgs} from '../src/agent-task-runner.js';
test('replay tool allowlist actually selects extension tool without unrelated tools',()=>{assert.deepEqual(agentTaskToolArgs({tools:'replay'}),['--tools','expert_replay']);assert.deepEqual(agentTaskToolArgs({tools:'trace'}),['--tools','trace_read']);});
import {expertReplayInputFromArchive,buildExpertReplayInvestigation,runExpertReplayInvestigation} from '../src/expert-replay-session.js';
import {writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
test('explicit complete task Skill and operating instructions are separately bound and delivered',async()=>{
 const root=await mkdtemp(join(tmpdir(),'replay-task-skill-')),taskPath=join(root,'task.md'),operationPath=join(root,'operation.txt');
 const taskText='Full task purpose.\nAllowed changes.\nSource authority.\nUnknown boundaries.\n',operation='Frozen generic operation text.\n',description='Exact task description';
 const sha=(s:string)=>createHash('sha256').update(s).digest('hex');
 await writeFile(taskPath,taskText);await writeFile(operationPath,operation);
 const input={description,taskBoundary:{priority:'explicit user purpose'},frozenPair:{mode:'style'},historicalObservations:{},currentCard:{},taskEvaluationSkill:{path:taskPath,sha256:sha(taskText),descriptionSha256:sha(description)},operatingInstruction:{path:operationPath,sha256:sha(operation)}};
 let captured:any;const run=await runExpertReplayInvestigation(input,{cwd:process.cwd(),provider:'mock',model:'mock',timeoutMs:1,rawEventsPath:'unused'},async o=>{captured=o;return {finalText:'offline',readPaths:[],toolNames:[],usage:{input:0,output:0,cacheRead:0,cacheWrite:0,totalTokens:0,costUsd:0},rawEventsPath:'unused'};});
 assert.ok(captured.systemPrompt.startsWith(operation));assert.ok(captured.systemPrompt.endsWith(taskText));
 assert.ok(captured.systemPrompt.includes('explicit user task boundary takes precedence'));
 assert.equal(run.taskEvaluationSkill?.sha256,sha(taskText));assert.equal(run.operatingSkill.sha256,sha(operation));
 assert.deepEqual(JSON.parse(captured.prompt).currentExplicitTaskBoundary,input.taskBoundary);
 const reversed=await buildExpertReplayInvestigation(process.cwd(),{...input,taskSkillPlacement:"before-operation"});assert.ok(reversed.systemPrompt.endsWith(operation));assert.equal(reversed.systemPrompt.split(taskText).length,2);assert.equal(reversed.prompt,captured.prompt);assert.notEqual(reversed.binding.systemSha256,run.binding.systemSha256);
 await assert.rejects(buildExpertReplayInvestigation(process.cwd(),{...input,description:'different'}),/Description binding/);
 await writeFile(taskPath,taskText+'drift');await assert.rejects(buildExpertReplayInvestigation(process.cwd(),input),/Skill content binding/);
 await writeFile(taskPath,taskText);await writeFile(operationPath,operation+'drift');await assert.rejects(buildExpertReplayInvestigation(process.cwd(),input),/operating instruction binding/);
});
test('real Replay entry consumes current Skill and explicit task boundary, not stale archived criteria',async()=>{const archive={pair:{mode:'style',sourceAspect:{evidences:[{quote:'source',location:'local'}]},targetAspect:{evidences:[{quote:'target',location:'local'}]}},publicEvidence:{events:[{output:{matched:false,rationale:'historical'}}]},criteria:{skill:{content:'STALE_RULE: Aligner receives matchRationale and no Evidence'}}};const contract={description:'Task requires clear professional prose.',taskPurpose:{style:'Allow equivalent clear prose; no fixed template.'}},before=JSON.stringify(archive),input=expertReplayInputFromArchive(archive,contract,{roleId:'refine.evidence-aligner'});let captured:any;const result=await runExpertReplayInvestigation(input,{cwd:process.cwd(),provider:'mock',model:'mock',timeoutMs:1,rawEventsPath:'unused'},async(o)=>{captured=o;return {finalText:'offline',readPaths:[],toolNames:[],usage:{input:0,output:0,cacheRead:0,cacheWrite:0,totalTokens:0,costUsd:0},rawEventsPath:'unused'};});assert.equal(captured.tools,'replay');const sent=JSON.parse(captured.prompt);assert.deepEqual(sent.frozenPair,archive.pair);assert.deepEqual(sent.historicalEvidence,archive.publicEvidence);assert.deepEqual(sent.currentExplicitTaskBoundary,contract.taskPurpose);assert.equal(sent.description,contract.description);assert.ok(!captured.prompt.includes('STALE_RULE'));assert.ok(captured.systemPrompt.includes('历史 matchRationale'));assert.ok(captured.systemPrompt.includes('两侧 Aspect 与相关 Evidence'));assert.ok(captured.systemPrompt.includes('理由错不自动翻转布尔'));assert.equal(JSON.stringify(archive),before);assert.equal(result.binding.version,'evidence-contract-v2');const changed=await buildExpertReplayInvestigation(process.cwd(),{...input,taskBoundary:{style:'different authorized boundary'}});assert.notEqual(changed.binding.promptSha256,result.binding.promptSha256);});
