import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,readFile,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
import{createExpertCardCopyStore,ALIGNER_ROLE as roleId}from'../src/expert-card-copy-store.js';
async function fixture(optIn=true,accountingClear=true){const root=await mkdtemp(join(tmpdir(),'draft-completion-')),source={roleId,systemPrompt:'base'};let calls=0,checks=0;
const options={maxUpdates:4,sampleCount:2,requirePriorBatch:true,allowUnstartedDraftCompletion:optIn,assertDraftAccountingClear:async()=>{checks++;if(!accountingClear)throw Error('accounting blocked');},receipt:async(id:string)=>({status:'settled' as const,requestId:id,costUsd:0,totalTokens:1,parsed:true})},store=createExpertCardCopyStore(root,source,async()=>{calls++;return{offline:true};},options);
await store.card({action:'create',roleId});await store.sample({roleId,version:'v0'});for(const parentVersion of ['v0','v1']){const v=await store.card({action:'update',roleId,parentVersion,systemPrompt:'prior '+parentVersion,reason:'setup'});await store.sample({roleId,version:v.version});}await store.card({action:'update',roleId,parentVersion:'v0',systemPrompt:'unstarted draft',reason:'setup'});
const proposal=JSON.parse(await readFile(new URL('./fixtures/expert-card-unstarted-draft-update.json',import.meta.url),'utf8'));assert.equal(proposal.source.requestId,214);return{root,store,args:{...proposal.arguments,roleId},calls:()=>calls,checks:()=>checks};}
test('exact paid214 proposal completes only an opt-in unstarted latest draft; immutable history and repeated update stay intact',async()=>{
 const f=await fixture(),before=await f.store.snapshot(),v4=await f.store.card(f.args),after=await f.store.snapshot();assert.equal(v4.version,'v4');assert.equal(v4.systemPrompt,f.args.systemPrompt);assert.equal(v4.reason,f.args.reason);assert.equal(v4.parent,f.args.parentVersion);assert.equal(v4.skill,before.versions.v3!.skill);assert.deepEqual(after.runs,before.runs);for(const id of Object.keys(before.versions))assert.deepEqual(after.versions[id],before.versions[id]);assert.equal(after.draftSupersessions?.v3?.successor,'v4');assert.equal(f.calls(),6);assert.equal(f.checks(),1);assert.deepEqual(await f.store.card(f.args),v4);assert.equal((await f.store.snapshot()).updates,4);assert.equal(f.checks(),1);assert.equal(f.calls(),6);
});
test('default closed, other parent, unknown version, wrong role, and unclear accounting cannot enter draft completion',async()=>{
 const defaultClosed=await fixture(false);await assert.rejects(defaultClosed.store.card(defaultClosed.args),/prior sample/);
 const f=await fixture();await assert.rejects(f.store.card({...f.args,parentVersion:'v0'}),/prior sample/);await assert.rejects(f.store.card({...f.args,parentVersion:'../v3'}),/Unknown/);await assert.rejects(f.store.card({...f.args,roleId:'wrong'}),/Role/);assert.equal(f.checks(),0);
 const blocked=await fixture(true,false);await assert.rejects(blocked.store.card(blocked.args),/accounting blocked/);assert.equal((await blocked.store.snapshot()).updates,3);
});
test('every started identity including not-sent/blocked/settled-success/parse-failure/unknown keeps the full prior-batch gate',async()=>{
 for(const status of ['not-sent','pre-send-blocked','running','settled-success','settled-parse-failure','unknown']){const f=await fixture(),state=await f.store.snapshot();state.runs.v3s1={runId:'v3s1',version:'v3',copyDigest:state.versions.v3!.digest,producerBinding:'fixture',status:status as any,...(status.startsWith('settled')?{receipt:{status:'settled' as const,requestId:'fixture',costUsd:0,totalTokens:1,parsed:status==='settled-success'}}:{})};await writeFile(join(f.root,'state.json'),JSON.stringify(state));await assert.rejects(f.store.card(f.args),/prior sample|Unresolved/);assert.equal(f.checks(),0);assert.equal((await f.store.snapshot()).updates,3);}
});
test('a frozen latest draft cannot use the no-trial completion path',async()=>{const f=await fixture(),state=await f.store.snapshot();state.freezes.fixture={version:'v3',copyDigest:state.versions.v3!.digest,runIds:[]};await writeFile(join(f.root,'state.json'),JSON.stringify(state));await assert.rejects(f.store.card(f.args),/prior sample/);assert.equal(f.checks(),0);});
