import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:http';
import {runPreparedCardReplayRecovery} from '../scripts/prepare-card-replay-recovery.js';
import {cardDigest,ALIGNER_ROLE} from '../src/expert-card-copy-store.js';
import {createExpertCardCopyStore} from '../src/expert-card-copy-store.js';
import {createCardReplayRuntime,registerCardReplayTools} from '../src/expert-card-replay-runtime.js';

test('actual prepared recovery entry restores paid prefix once and resolves missing artifact filename offline',{timeout:90000},async()=>{
 const root=await mkdtemp(join(tmpdir(),'actual-card-resume-')),requests:any[]=[];
 const server=createServer(async(req,res)=>{let raw='';for await(const b of req)raw+=b;requests.push(JSON.parse(raw));const n=requests.length;
 const delta=n===1?{role:'assistant',tool_calls:[{index:0,id:'new_read',type:'function',function:{name:'expert_evidence',arguments:JSON.stringify({kind:'artifact',id:'v5s1'})}}]}:{role:'assistant',content:'Recovered report'};
 res.writeHead(200,{'content-type':'text/event-stream'});res.write(`data: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',model:'recovery-fake',choices:[{index:0,delta,finish_reason:null}]})}\n\n`);res.end(`data: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',model:'recovery-fake',choices:[{index:0,delta:{},finish_reason:n===1?'tool_calls':'stop'}],usage:{prompt_tokens:0,completion_tokens:0,total_tokens:0}})}\n\ndata: [DONE]\n\n`);
 });await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${(server.address() as any).port}`;
 const provider=join(root,'provider.ts'),guard=join(root,'guard.ts'),budget=join(root,'budget');await mkdir(budget);await writeFile(join(budget,'provider-budget.json'),JSON.stringify({requests:0,inFlight:{},usage:{costUsd:0},limits:{costUsd:0}}));
 await writeFile(provider,`export default function(pi){pi.registerProvider('recovery-offline',{baseUrl:'${origin}/v1',apiKey:'offline',api:'openai-completions',models:[{id:'recovery-fake',name:'Offline',reasoning:false,input:['text'],contextWindow:200000,maxTokens:1000,cost:{input:0,output:0,cacheRead:0,cacheWrite:0},compat:{supportsDeveloperRole:false}}]});}`);
 // A zero-cost reservation fixture, never the real ledger or remote transport.
 await writeFile(guard,`import fs from 'node:fs';export function guard(pi,root){const p=root+'/provider-budget.json';pi.on('before_provider_request',()=>{const s=JSON.parse(fs.readFileSync(p,'utf8'));s.inFlight[++s.requests]={cost:0};fs.writeFileSync(p,JSON.stringify(s));});pi.on('message_end',e=>{if(e.message.role==='assistant'){const s=JSON.parse(fs.readFileSync(p,'utf8'));delete s.inFlight[s.requests];fs.writeFileSync(p,JSON.stringify(s));}});}`);
 const output=join(root,'sample.md');await writeFile(output,'Existing paid Expert output');
 const prompt='ORIGINAL RUNTIME '+ 'material '.repeat(2300),system='Original system'; // Exercise @file transport too.
 const prefix=[{role:'system',content:system},{role:'user',content:[{type:'text',text:prompt}]},{role:'assistant',content:'Paid previous observation'}];
 const config={allowPaidProvider:true,sessionOutputRoot:join(root,'session-output'),runtime:{root,source:{roleId:ALIGNER_ROLE,systemPrompt:'Card'},storeOptions:{maxUpdates:6,executionBinding:'fixture'},evidence:{sessions:{},artifacts:{'v5s1/public-output.md':{path:output,sha256:cardDigest('Existing paid Expert output')}},defaultArtifacts:{v5s1:'v5s1/public-output.md'}},readOnly:true},system,prompt,prefix,provider:'recovery-offline',model:'recovery-fake',maxOutputTokens:1000,thinking:'off',budgetRoot:budget,budgetGuardPath:guard,phase:'offline',providerOrigin:origin,maxRequests:3,providerExtension:provider,bindings:[]};
 const path=join(root,'config.json');await writeFile(path,JSON.stringify(config));
 const envPath=process.env.EXPERT_CARD_REPLAY_CONFIG,envHash=process.env.EXPERT_CARD_REPLAY_CONFIG_SHA256;
 try{const result=await runPreparedCardReplayRecovery(path);assert.equal(result.finalText,'Recovered report');assert.equal(requests.length,2);
 assert(result.rawEventsPath.startsWith(config.sessionOutputRoot));assert(result.completion.assessmentPath.startsWith(config.sessionOutputRoot));assert.equal(config.runtime.root,root);
 assert.equal(result.completion.objectiveStatus,'objective-not-achieved');assert.equal(result.completion.newVerifiedLiveAttempts,0);assert.equal(result.completion.executionStatus,'incomplete');
 assert.equal(JSON.parse(await readFile(result.completion.assessmentPath,'utf8')).mode,'paid-prefix-resume');
 for(const r of requests){assert.deepEqual(r.messages.slice(0,prefix.length),prefix);assert.equal(r.messages.filter((m:any)=>m.role==='user').length,1);assert.equal(r.messages.filter((m:any)=>m.content==='Paid previous observation').length,1);}
 assert(requests[1].messages.some((m:any)=>m.role==='tool'&&m.content.includes('Existing paid Expert output')));
 assert.equal(JSON.parse(await readFile(join(budget,'provider-budget.json'),'utf8')).usage.costUsd,0);
 }finally{if(envPath===undefined)delete process.env.EXPERT_CARD_REPLAY_CONFIG;else process.env.EXPERT_CARD_REPLAY_CONFIG=envPath;if(envHash===undefined)delete process.env.EXPERT_CARD_REPLAY_CONFIG_SHA256;else process.env.EXPERT_CARD_REPLAY_CONFIG_SHA256=envHash;server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
});

async function generationEntry(mode:'final'|'update') {
 const root=await mkdtemp(join(tmpdir(),'generation-entry-')),budget=join(root,'budget'),copies=join(root,'copies');await mkdir(budget);await writeFile(join(budget,'provider-budget.json'),JSON.stringify({requests:0,inFlight:{},usage:{costUsd:0},limits:{costUsd:1},blocked:null,accountingUnknown:null}));
 let expertCalls=0;const store=createExpertCardCopyStore(copies,{roleId:ALIGNER_ROLE,systemPrompt:'BASE'},async()=>{expertCalls++;throw Error('Expert must not run');},{sampleCount:1,receipt:async()=>({status:'unknown'})});const v0=await store.card({action:'create',roleId:ALIGNER_ROLE});
 // Seed the required baseline without a provider; this is only a local entry-contract fixture.
 const state=await store.snapshot();state.runs.baseline1={runId:'baseline1',version:'v0',copyDigest:v0.digest,producerBinding:cardDigest({execution:'fixture',copyDigest:v0.digest}),status:'settled-success',receipt:{status:'settled',requestId:'fixture',costUsd:0,totalTokens:0,parsed:true}};await writeFile(join(copies,'state.json'),JSON.stringify(state));
 const authorization={id:'entry-generation',allowedNewVersions:['v1'],originVersions:{v0:v0.digest},requireReadyForTrial:true,allowConfirmation:false};
 const runtimeConfig:any={root,source:{roleId:ALIGNER_ROLE,systemPrompt:'BASE'},generationOnly:true,storeOptions:{maxUpdates:1,sampleCount:1,requirePriorBatch:true,reviewedCopies:{},executionBinding:'fixture',trialAuthorization:authorization},evidence:{sessions:{},artifacts:{},defaultArtifacts:{}}};
 const config:any={allowPaidProvider:true,sessionOutputRoot:root,runtime:runtimeConfig,system:'system',prompt:'prompt',provider:'offline',model:'offline',maxOutputTokens:8000,thinking:'off',budgetRoot:budget,budgetGuardPath:join(root,'unused-guard.ts'),phase:'offline-generation',providerOrigin:'http://127.0.0.1',maxRequests:1,providerExtension:join(root,'unused-provider.ts'),bindings:[]};const configPath=join(root,'config.json');await writeFile(configPath,JSON.stringify(config));
 let runnerCalls=0;const runner=async(options:any)=>{runnerCalls++;const runtime=createCardReplayRuntime({...runtimeConfig,settledTrialEvidence:{budgetRoot:budget}},async()=>{expertCalls++;throw Error('Expert must not run');});const tools:any[]=[];const handlers:any={};registerCardReplayTools({registerTool:(tool:any)=>tools.push(tool),on:(name:string,handler:any)=>handlers[name]=handler,setActiveTools(){}},runtime,join(root,'engineering-stop.json'));
   if(mode==='update'){const card=tools.find(t=>t.name==='expert_card_copy');await card.execute('update',{action:'update',parentVersion:'v0',fewShotCases:[{syntheticTaskRequirement:'fixture',mode:'content',sourceAspect:{id:'s',title:'s',description:'s',evidences:[{quote:'complete source',location:'s'}]},targetAspect:{id:'t',title:'t',description:'t',evidences:[{quote:'complete target',location:'t'}]},expectedMatched:true,evidenceRationale:[{side:'source',evidenceIndex:0,quotedText:'source',explanation:'fixture'},{side:'target',evidenceIndex:0,quotedText:'target',explanation:'fixture'}],whyBoundaryApplies:'fixture',scope:'fixture'}],reason:'fixture',readyForTrial:true});await writeFile(options.rawEventsPath,JSON.stringify({type:'message_end',message:{role:'assistant',stopReason:'toolUse',content:[{type:'toolCall',name:'expert_card_copy'}]}})+'\n');throw Error('planned pause interrupted the next provider request');}
   await writeFile(options.rawEventsPath,JSON.stringify({type:'message_end',message:{role:'assistant',stopReason:'stop',content:[{type:'text',text:'I saved it'}]}})+'\n');return{finalText:'I saved it',stopReason:'stop',rawEventsPath:options.rawEventsPath,readPaths:[],toolNames:[],usage:{input:0,output:0,cacheRead:0,cacheWrite:0,totalTokens:0,costUsd:0}};};
 const result=await runPreparedCardReplayRecovery(configPath,runner as any);return{root,budget,result,runnerCalls,expertCalls,state:JSON.parse(await readFile(join(copies,'state.json'),'utf8')),persisted:JSON.parse(await readFile(join(root,'resumed-result.json'),'utf8'))};
}
test('generation entry does not retry a prose-only final and persists an explicit incomplete terminal',async()=>{const f=await generationEntry('final');assert.equal(f.runnerCalls,1);assert.equal(f.expertCalls,0);assert.equal(f.result.terminalStatus,'generation-incomplete');assert.equal(f.result.automaticRetry,false);assert.equal(f.persisted.terminalStatus,'generation-incomplete');assert.deepEqual(f.state.runs&&Object.keys(f.state.runs),['baseline1']);assert.deepEqual(JSON.parse(await readFile(join(f.budget,'provider-budget.json'),'utf8')).inFlight,{});});
test('generation entry normalizes a verified planned pause into a consumable review terminal with no trial',async()=>{const f=await generationEntry('update');assert.equal(f.runnerCalls,1);assert.equal(f.expertCalls,0);assert.equal(f.result.terminalStatus,'candidate-saved-awaiting-review');assert.equal(f.result.completion.generation.checks.pauseMatches,true);assert.equal(f.persisted.terminalStatus,'candidate-saved-awaiting-review');assert.deepEqual(Object.keys(f.state.runs),['baseline1']);assert.deepEqual(f.state.freezes,{});assert.deepEqual(JSON.parse(await readFile(join(f.budget,'provider-budget.json'),'utf8')).inFlight,{});});
