import test from'node:test';import assert from'node:assert/strict';import{mkdtemp,readFile,writeFile,mkdir}from'node:fs/promises';import{existsSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';
import{Check}from'typebox/value';import{fewShotCasesSchema,validateFewShotCases,renderFewShotCases,type FewShotCase}from'../src/expert-card-few-shot.js';
import{createExpertCardCopyStore,applyCardCopy,cardDigest,ALIGNER_ROLE as roleId}from'../src/expert-card-copy-store.js';import{createCardReplayRuntime,registerCardReplayTools}from'../src/expert-card-replay-runtime.js';
// Serialization sentinels only: never supplied to an experimental model or treated as judgments.
const example=():FewShotCase=>({syntheticTaskRequirement:'offline engineering fixture',mode:'style',sourceAspect:{id:'s',title:'source',description:'fixture',evidences:[{quote:'SRC "quoted"\n\\ literal',location:'source location'}]},targetAspect:{id:'t',title:'target',description:'fixture',evidences:[{quote:'TGT <raw> text',location:'target location'}]},expectedMatched:true,evidenceRationale:[{side:'source',evidenceIndex:0,quotedText:'"quoted"',explanation:'source mapping fixture'},{side:'target',evidenceIndex:0,quotedText:'<raw>',explanation:'target mapping fixture'}],whyBoundaryApplies:'fixture string, not semantic evidence',scope:'offline only'});
test('structured schema and reference mapping reject missing/wrong-side data without pretending to detect prose or labels',()=>{
 const item=example();assert(Check(fewShotCasesSchema,[item]));validateFewShotCases([item]);assert.equal(renderFewShotCases(undefined),'');assert.equal(renderFewShotCases([]),'');assert.deepEqual(JSON.parse(renderFewShotCases([item]).split('：\n')[1]!),[item]);
 for(const mutate of [(x:any)=>delete x.targetAspect,(x:any)=>x.expectedMatched='true',(x:any)=>x.sourceAspect.evidences=[],(x:any)=>x.scope='   ',(x:any)=>x.evidenceRationale[0].evidenceIndex=99,(x:any)=>x.evidenceRationale[0].quotedText='<raw>',(x:any)=>x.evidenceRationale[1].side='source']){const bad=structuredClone(item);mutate(bad);assert.throws(()=>validateFewShotCases([bad]));}
 const overview=example();overview.sourceAspect.evidences[0]!.quote='属性概述，不是完整正文';overview.evidenceRationale[0]!.quotedText='属性概述';validateFewShotCases([overview]); // Must remain an operator review issue.
});
test('structured fields inherit, replace and clear immutably; legacy digests and rendered suffix stay exact',async()=>{
 const root=await mkdtemp(join(tmpdir(),'fewshot-fields-')),source={roleId,systemPrompt:'BASE'},store=createExpertCardCopyStore(root,source,async()=>{throw Error('offline');},{maxUpdates:5});const v0=await store.card({action:'create',roleId});const before=JSON.stringify(v0);
 const args={action:'update' as const,roleId,parentVersion:'v0',fewShotCases:[example()],reason:'fixture'};const v1=await store.card(args);assert.equal(v1.systemPrompt,'BASE');assert.equal(v1.skill,'');assert.equal(applyCardCopy('BASE\nTAIL','BASE',v1),'BASE'+renderFewShotCases(v1.fewShotCases)+'\nTAIL');assert.deepEqual(await store.card(args),v1);
 const v2=await store.card({action:'update',roleId,parentVersion:'v1',systemPrompt:'NEW',reason:'partial'});assert.deepEqual(v2.fewShotCases,v1.fewShotCases);
 const changed=example();changed.scope='other fixture';const v3=await store.card({action:'update',roleId,parentVersion:'v2',fewShotCases:[changed],reason:'replace'});assert.notEqual(v3.digest,v2.digest);assert.equal(v3.systemPrompt,'NEW');
 const v4=await store.card({action:'update',roleId,parentVersion:'v3',fewShotCases:[],reason:'clear'});assert.deepEqual(v4.fewShotCases,[]);assert.equal(applyCardCopy('BASE\nTAIL','BASE',v4),'NEW\nTAIL');assert.equal(JSON.stringify((await store.snapshot()).versions.v0),before);assert(!Object.hasOwn(v0,'fewShotCases'));assert.deepEqual((await store.snapshot()).versions.v1,v1);
});
async function generation(){const root=await mkdtemp(join(tmpdir(),'generation-stage-')),source={roleId,systemPrompt:'BASE'},budget=join(root,'budget');await mkdir(budget);await writeFile(join(budget,'provider-budget.json'),JSON.stringify({inFlight:{}}));await writeFile(join(budget,'provider-events.jsonl'),'');let calls=0;
 const receipt=async(id:string)=>({status:'settled' as const,requestId:id,costUsd:0,totalTokens:1,parsed:true}),execute=async()=>{calls++;return{fixture:true};},old=createExpertCardCopyStore(join(root,'copies'),source,execute,{sampleCount:2,receipt});const v0=await old.card({action:'create',roleId});await old.sample({roleId,version:'v0'});const baseCalls=calls;
 const config={root,source,generationOnly:true,storeOptions:{maxUpdates:1,sampleCount:2,requirePriorBatch:true,reviewedCopies:{},receipt,trialAuthorization:{id:'generation-phase',allowedNewVersions:['v1'],originVersions:{v0:v0.digest},requireReadyForTrial:true,allowConfirmation:false}},evidence:{sessions:{},artifacts:{},defaultArtifacts:{}},settledTrialEvidence:{root,budgetRoot:budget,phasePrefix:'fixture',baselineRequestPath:join(root,'unused-baseline.json'),sourcePrompt:'BASE'} as any};
 const runtime=createCardReplayRuntime(config,execute),tools:any[]=[],handlers:any={},stopPath=join(root,'engineering-stop.json');let active:string[]=[];const stop=registerCardReplayTools({registerTool:(t:any)=>tools.push(t),on:(n:string,h:any)=>handlers[n]=h,setActiveTools:(x:string[])=>active=x},runtime,stopPath);
 return{root,config,runtime,tools,handlers,stop,stopPath,active:()=>active,calls:()=>calls-baseCalls,execute,update:{action:'update' as const,parentVersion:'v0',systemPrompt:'fixture duties',fewShotCases:[example()],reason:'fixture only',readyForTrial:true}};
}
test('generation success returns exact candidate then planned pause blocks subsequent tools/provider, with no trial tool or engineering failure',async()=>{
 const contract=await generation();const inventory=await contract.runtime.store.quota();assert.deepEqual(inventory.updatePrerequisites,{requirePriorBatch:true,baselineBatchComplete:true,latestVersion:'v0',latestBatchComplete:true});const publicInventory:any=await contract.runtime.evidence({kind:'inventory'});assert.deepEqual(publicInventory.completionContract,{requiredAction:'expert_card_copy.update',requiresMatchingCandidateReviewPause:true,proseFinalWithoutReceipt:'generation-incomplete',automaticRetry:false});assert.match(contract.tools.find(t=>t.name==='expert_card_copy').description,/including v0/);assert.match(contract.tools.find(t=>t.name==='expert_card_copy').description,/gates are global/);assert.match(contract.tools.find(t=>t.name==='expert_card_copy').description,/prose final.*generation-incomplete/i);assert.match(contract.tools.find(t=>t.name==='expert_evidence').description,/recorded run only/);
 const f=await generation();f.handlers.session_start();assert.deepEqual(f.active(),['expert_card_copy','expert_evidence']);assert(!f.tools.some(t=>t.name==='expert_trial'));const card=f.tools.find(t=>t.name==='expert_card_copy');assert(Check(card.parameters,f.update));const result=await card.execute('generated',f.update),copy=JSON.parse(result.content[0].text);assert.equal(copy.version,'v1');assert.deepEqual(copy.fewShotCases,f.update.fewShotCases);
 const pause=JSON.parse(await readFile(join(f.root,'candidate-review-pause.json'),'utf8'));assert.equal(pause.kind,'planned-candidate-review-pause');assert.equal(pause.copyDigest,copy.digest);assert(!existsSync(f.stopPath));await assert.rejects(f.tools.find(t=>t.name==='expert_evidence').execute('later',{kind:'inventory'}),/Planned candidate review pause/);
 let aborted=false;assert.throws(()=>f.handlers.before_provider_request({}, {abort(){aborted=true;}}),/Planned candidate review pause/);assert(aborted);f.stop.reject('aborted due planned pause');assert(!existsSync(f.stopPath));assert.equal(f.calls(),0);
});
test('store review gate blocks batch/replay/freeze/confirm and same-batch update bypass; approval is digest-bound, not a rewrite',async()=>{
 const f=await generation(),copy=await f.runtime.store.card({...f.update,roleId});for(const action of ['sample','freeze','confirm'] as const)await assert.rejects(f.runtime.store[action]({roleId,version:'v1',selectionId:'attempt'}),/review|forbids/);await assert.rejects(f.runtime.store.replay({roleId,version:'v1',runId:'v1s1'}),/review/);assert.equal(f.calls(),0);assert(!(await f.runtime.store.snapshot()).runs.v1s1);
 const wrong=createCardReplayRuntime({...f.config,generationOnly:false,storeOptions:{...f.config.storeOptions,reviewedCopies:{v1:'0'.repeat(64)}}},f.execute);await assert.rejects(wrong.store.sample({roleId,version:'v1'}),/review/);
 const approved=createCardReplayRuntime({...f.config,generationOnly:false,storeOptions:{...f.config.storeOptions,reviewedCopies:{v1:copy.digest}}},f.execute);assert.deepEqual(await approved.store.card({...f.update,roleId}),copy);await approved.store.sample({roleId,version:'v1'});assert.equal(f.calls(),2);assert((await approved.store.sample({roleId,version:'v1'})).every(r=>r.delivery==='cached-existing'));assert.equal(f.calls(),2);
 assert.throws(()=>createCardReplayRuntime({...f.config,storeOptions:{...f.config.storeOptions,reviewedCopies:{v1:copy.digest}}},f.execute),/empty operator review/);
});
