import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {copyFile,mkdtemp,mkdir,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createExpertCardCopyStore,ALIGNER_ROLE,cardDigest} from '../src/expert-card-copy-store.js';
import {freezeSeparatedObservation,prepareSeparatedModificationStage,prepareSeparatedObservationStage,runPreparedCardReplayRecovery} from '../scripts/prepare-card-replay-recovery.js';
import {createCardReplayRuntime,registerCardReplayTools,separatedModificationDecisionToken} from '../src/expert-card-replay-runtime.js';

test('loopback shadow runs isolated observation then fresh update or explicit bound no-change',{timeout:90000},async()=>{
 const root=await mkdtemp(join(tmpdir(),'separated-shadow-')),shadow=join(root,'shadow'),budget=join(root,'budget'),requests:any[]=[];let noChangeBinding:any;await mkdir(budget);await writeFile(join(budget,'provider-budget.json'),JSON.stringify({requests:2,inFlight:{},usage:{costUsd:0},limits:{costUsd:1},blocked:null,accountingUnknown:null}));await writeFile(join(budget,'provider-events.jsonl'),`${JSON.stringify({type:'admit',id:1,phase:'shadow-expert-baseline1'})}\n${JSON.stringify({type:'settled',id:1,phase:'shadow-expert-baseline1',actual:{costUsd:0,totalTokens:1}})}\n${JSON.stringify({type:'admit',id:2,phase:'shadow-expert-baseline2'})}\n${JSON.stringify({type:'settled',id:2,phase:'shadow-expert-baseline2',actual:{costUsd:0,totalTokens:1}})}\n`);
 const sourcePath=join(root,'source.md'),sourceText='COMPLETE SOURCE with exact source quote.';await writeFile(sourcePath,sourceText);
 const server=createServer(async(req,res)=>{let raw='';for await(const chunk of req)raw+=chunk;const request=JSON.parse(raw);requests.push(request);const user=request.messages.find((m:any)=>m.role==='user');const prompt=typeof user.content==='string'?user.content:user.content.map((b:any)=>b.text).join('');const stage=prompt.includes('DIAGNOSE')?'diagnosis':prompt.includes('NO CHANGE')?'no-change':'modification',marker=stage==='diagnosis'?'DIAGNOSE':stage==='no-change'?'NO CHANGE':'MODIFY',prior=requests.filter(r=>{const u=r.messages.find((m:any)=>m.role==='user');return (typeof u.content==='string'?u.content:u.content.map((b:any)=>b.text).join('')).includes(marker);}).length;
  let delta:any,finish='tool_calls';
  if(stage==='diagnosis'&&prior===1)delta={role:'assistant',tool_calls:[{index:0,id:'read_source',type:'function',function:{name:'expert_evidence',arguments:JSON.stringify({kind:'artifact',id:'source'})}}]};
  else if(stage==='diagnosis'){delta={role:'assistant',content:'S1 ORIGINAL: exact source quote; uncertainty remains.'};finish='stop';}
  else if(stage==='no-change'&&prior===1)delta={role:'assistant',tool_calls:[{index:0,id:'inventory',type:'function',function:{name:'expert_evidence',arguments:JSON.stringify({kind:'inventory'})}}]};
  else if(prior===1)delta={role:'assistant',tool_calls:[{index:0,id:'read_receipt',type:'function',function:{name:'expert_evidence',arguments:JSON.stringify({kind:'artifact',id:'diagnosis'})}},{index:1,id:'read_parent',type:'function',function:{name:'expert_card_read',arguments:'{}'}}]};
  else if(stage==='no-change'&&prior===2)delta={role:'assistant',tool_calls:[{index:0,id:'read_receipt',type:'function',function:{name:'expert_evidence',arguments:JSON.stringify({kind:'artifact',id:'diagnosis'})}},{index:1,id:'read_parent',type:'function',function:{name:'expert_card_read',arguments:'{}'}}]};
  else if(stage==='no-change')delta={role:'assistant',tool_calls:[{index:0,id:'no_change',type:'function',function:{name:'expert_card_no_change',arguments:JSON.stringify({reason:'ORIGINAL NO CHANGE REASON'})}}]};
  else delta={role:'assistant',tool_calls:[{index:0,id:'update',type:'function',function:{name:'expert_card_update',arguments:JSON.stringify({cardSkill:'local shadow change',reason:'loopback infrastructure fixture, not semantic evidence',fewShotCases:[{syntheticTaskRequirement:'Compare two synthetic notices.',mode:'style',sourceText:'alpha complete text',targetText:'beta complete text',expectedMatched:true,evidenceRationale:[{side:'source',quotedText:'alpha',explanation:'fixture source quote'},{side:'target',quotedText:'beta',explanation:'fixture target quote'}],whyBoundaryApplies:'fixture only',scope:'loopback only'}]})}}]};
  res.writeHead(200,{'content-type':'text/event-stream'});res.write(`data: ${JSON.stringify({id:'shadow',object:'chat.completion.chunk',model:'shadow-fake',choices:[{index:0,delta,finish_reason:null}]})}\n\n`);res.end(`data: ${JSON.stringify({id:'shadow',object:'chat.completion.chunk',model:'shadow-fake',choices:[{index:0,delta:{},finish_reason:finish}],usage:{prompt_tokens:0,completion_tokens:0,total_tokens:0}})}\n\ndata: [DONE]\n\n`);
 });await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const origin=`http://127.0.0.1:${(server.address() as any).port}`;
 const provider=join(root,'provider.ts'),guard=join(root,'guard.ts');await writeFile(provider,`export default function(pi){pi.registerProvider('shadow',{baseUrl:'${origin}/v1',apiKey:'offline',api:'openai-completions',models:[{id:'shadow-fake',name:'Shadow',reasoning:false,input:['text'],contextWindow:200000,maxTokens:1000,cost:{input:0,output:0,cacheRead:0,cacheWrite:0}}]});}`);await writeFile(guard,`import fs from 'node:fs';export function guard(pi,root,phase){const p=root+'/provider-budget.json',e=root+'/provider-events.jsonl';let id;pi.on('before_provider_request',ev=>{const s=JSON.parse(fs.readFileSync(p,'utf8'));id=++s.requests;s.inFlight[id]={cost:0};fs.writeFileSync(p,JSON.stringify(s));fs.appendFileSync(e,JSON.stringify({type:'admit',id,phase})+'\\n');});pi.on('message_end',ev=>{if(ev.message.role==='assistant'){const s=JSON.parse(fs.readFileSync(p,'utf8'));delete s.inFlight[id];fs.writeFileSync(p,JSON.stringify(s));fs.appendFileSync(e,JSON.stringify({type:'settled',id,phase,actual:{costUsd:0,totalTokens:0}})+'\\n');}});}`);
 const copiesRoot=join(root,'copies-root'),source={roleId:ALIGNER_ROLE,systemPrompt:'HISTORY_SENTINEL'};const seed=createExpertCardCopyStore(join(copiesRoot,'copies'),source,async()=>{} ,{maxUpdates:2});const v0=await seed.card({action:'create',roleId:ALIGNER_ROLE});const v1=await seed.card({action:'update',roleId:ALIGNER_ROLE,parentVersion:'v0',systemPrompt:'AUTHORIZED PARENT',reason:'seed'});
 const executionBinding='fixture-execution',baselinePayload={model:'shadow-fake',messages:[{role:'system',content:source.systemPrompt},{role:'user',content:'PAIR'}],max_tokens:1000},baselineOptions=join(root,'baseline-options.json'),baselineRequest=join(root,'baseline-request.json'),baselineTrial=join(copiesRoot,'trials','baseline1');await writeFile(baselineOptions,JSON.stringify({cwd:root,provider:'shadow',model:'shadow-fake',systemPrompt:source.systemPrompt,prompt:'PAIR',maxOutputTokens:1000}));await writeFile(baselineRequest,JSON.stringify(baselinePayload));await writeFile(join(budget,'provider-request-000001.json'),JSON.stringify(baselinePayload));await mkdir(baselineTrial,{recursive:true});await writeFile(join(baselineTrial,'actual-request.json'),JSON.stringify(baselinePayload));const seededState=JSON.parse(await readFile(join(copiesRoot,'copies','state.json'),'utf8'));seededState.runs.baseline1={runId:'baseline1',version:'v0',copyDigest:v0.digest,producerBinding:cardDigest({execution:executionBinding,copyDigest:v0.digest}),status:'settled-success',receipt:{status:'settled',requestId:'1',costUsd:0,totalTokens:1,parsed:true}};seededState.runs.baseline2={runId:'baseline2',version:'v0',copyDigest:v0.digest,producerBinding:cardDigest({execution:executionBinding,copyDigest:v0.digest}),status:'settled-success',receipt:{status:'settled',requestId:'2',costUsd:0,totalTokens:1,parsed:true}};await writeFile(join(copiesRoot,'copies','state.json'),JSON.stringify(seededState,null,2));
 const expertExecution={root:copiesRoot,sourcePrompt:source.systemPrompt,baselineOptionsPath:baselineOptions,baselineRequestPath:baselineRequest,budgetRoot:budget,budgetGuardPath:guard,providerExtension:provider,providerOrigin:origin,phasePrefix:'shadow-expert'};
 const authorization={id:'shadow',allowedNewVersions:['v2'],originVersions:{v0:v0.digest,v1:v1.digest},requireReadyForTrial:true,allowConfirmation:false};const baseConfig={runtime:{root:copiesRoot,source,storeOptions:{maxUpdates:2,executionBinding,reviewedCopies:{},trialAuthorization:authorization},evidence:{sessions:{},artifacts:{},defaultArtifacts:{}}},provider:'shadow',model:'shadow-fake',maxOutputTokens:1000,thinking:'off',budgetRoot:budget,budgetGuardPath:guard,phase:'shadow',providerOrigin:origin,maxRequests:4,providerExtension:provider,expertExecution,bindings:[]};
 const diag=prepareSeparatedObservationStage({baseConfig,outputRoot:shadow,system:'DIAG SYSTEM',prompt:'DIAGNOSE',allowProvider:true},{source:{path:sourcePath,sha256:cardDigest(sourceText),scope:'cached full text'}});const diagResult=await runPreparedCardReplayRecovery(diag.path);const frozen=freezeSeparatedObservation(diag.path,diagResult,[{sourceId:'source',quotedText:'exact source quote'}],['Card instructions were intentionally not visible.']);
 const mod=prepareSeparatedModificationStage({baseConfig,outputRoot:shadow,system:'MOD SYSTEM',prompt:'MODIFY',allowProvider:true},{artifacts:{source:{path:sourcePath,sha256:cardDigest(sourceText),scope:'cached full text'}},receiptPath:frozen.path,receiptSha256:frozen.sha256,parentVersion:'v1'});const modResult=await runPreparedCardReplayRecovery(mod.path);
 const noChangeRoot=join(shadow,'no-change'),noChange=prepareSeparatedModificationStage({baseConfig,outputRoot:noChangeRoot,system:'MOD SYSTEM',prompt:'NO CHANGE',allowProvider:true},{artifacts:{source:{path:sourcePath,sha256:cardDigest(sourceText),scope:'cached full text'}},receiptPath:frozen.path,receiptSha256:frozen.sha256,parentVersion:'v1'}),noChangeConfig=JSON.parse(await readFile(noChange.path,'utf8')),noChangeDecision=noChangeConfig.runtime.separatedModificationDecision,noChangeRawBinding={observationReceiptSha256:frozen.sha256,parentVersion:'v1',parentDigest:v1.digest};assert.deepEqual({...noChangeDecision,startStateSha256:undefined},{...noChangeRawBinding,startStateSha256:undefined});noChangeBinding={decisionToken:separatedModificationDecisionToken(noChangeDecision)};const noChangeResult=await runPreparedCardReplayRecovery(noChange.path);
 try{assert.equal(modResult.terminalStatus,'candidate-saved-awaiting-review');assert.equal(noChangeResult.terminalStatus,'no-change-decision-recorded');assert.equal(noChangeResult.completion.generation.reason,'ORIGINAL NO CHANGE REASON');const noChangeReceipt=JSON.parse(await readFile(join(noChangeRoot,'modification','modification-no-change-receipt.json'),'utf8'));assert.deepEqual({...noChangeReceipt,at:undefined},{kind:'separated-modification-no-change',...noChangeRawBinding,reason:'ORIGINAL NO CHANGE REASON',at:undefined});const serialized=JSON.stringify(requests);assert(!serialized.includes('HISTORY_SENTINEL'));assert.equal(requests.every(r=>r.messages.filter((m:any)=>m.role==='user').length===1),true);assert(requests.some(r=>JSON.stringify(r).includes('S1 ORIGINAL')));assert(requests.some(r=>JSON.stringify(r).includes('AUTHORIZED PARENT')));assert.equal(Object.keys((await seed.snapshot()).runs).length,2);assert.equal((await seed.snapshot()).versions.v2!.parent,'v1');const preparedModification=JSON.parse(await readFile(mod.path,'utf8'));assert.equal(preparedModification.prefix,undefined);assert.equal(preparedModification.runtime.settledTrialEvidence.phasePrefix,'shadow-expert');assert.equal(preparedModification.expertExecution.phasePrefix,'shadow-expert');assert.equal(preparedModification.separatedAccountingEvidence.requestId,'1');assert.equal(preparedModification.runtime.evidence.artifacts['baseline1/actual-request.json'],undefined);
  const diagnosisRequest=requests.find(request=>request.messages.some((message:any)=>message.role==='user'&&(typeof message.content==='string'?message.content:message.content.map((block:any)=>block.text).join('')).includes('DIAGNOSE'))),modificationRequest=requests.find(request=>request.messages.some((message:any)=>message.role==='user'&&(typeof message.content==='string'?message.content:message.content.map((block:any)=>block.text).join('')).includes('MODIFY'))),diagnosisSystem=diagnosisRequest.messages[0].content,modificationSystem=modificationRequest.messages[0].content,definitions=modificationRequest.tools.map((tool:any)=>tool.function),evidenceDefinition=definitions.find((tool:any)=>tool.name==='expert_evidence'),cardDefinition=definitions.find((tool:any)=>tool.name==='expert_card_update');
  assert(!JSON.stringify(evidenceDefinition.parameters).includes('version'));assert.equal(preparedModification.runtime.modificationToolContract,'compact-v1');assert.deepEqual(definitions.map((tool:any)=>tool.name).sort(),['expert_card_no_change','expert_card_read','expert_card_update','expert_evidence']);assert.doesNotMatch(JSON.stringify(definitions),/decisionToken|roleId|parentVersion|readyForTrial/);
  const noChangeSchema=definitions.find((tool:any)=>tool.name==='expert_card_no_change').parameters;assert.deepEqual(Object.keys(noChangeSchema.properties),['reason']);assert.deepEqual(noChangeSchema.required,['reason']);assert.equal(cardDefinition.parameters.type,'object');
  const deliveredInventory=requests.flatMap(request=>request.messages.filter((message:any)=>message.role==='tool').map((message:any)=>{try{return JSON.parse(typeof message.content==='string'?message.content:message.content.map((block:any)=>block.text).join(''));}catch{return undefined;}})).find((value:any)=>value?.completion);assert.deepEqual(deliveredInventory.cardAccess,{tool:'expert_card_read'});assert.equal(deliveredInventory.noChangeAction,undefined);
  assert.match(diagnosisSystem,/材料直接证明的局部问题/);assert.match(diagnosisSystem,/材料直接证明的正常行为/);assert.match(diagnosisSystem,/证据不足而不能定性/);assert.match(diagnosisSystem,/完整文稿只给 Harness 提供诊断背景/);assert.match(diagnosisSystem,/已结算 Expert 投影只表示该次局部调用实际收到的输入/);assert.match(diagnosisSystem,/第一轮并行读取/);assert.match(diagnosisSystem,/不要产出 Gold、Card 补丁、当前 pair 的预期答案、few-shot 或修复案例/);assert.match(diagnosisSystem,/Skill 中的例子不是穷尽条件/);assert.match(diagnosisSystem,/Description 的全篇写作目标/);
  assert.match(modificationSystem,/task-derived requirements/);assert.match(modificationSystem,/supported、unsupported 或 unknown/);assert.match(modificationSystem,/parent 文字、parent few-shot、未找到反例都不能证明 parent 正确/);assert.match(modificationSystem,/信息不足保持 unknown/);assert.match(modificationSystem,/不得推出当前 pair 标签或宣称 parent 合规/);assert.match(modificationSystem,/expert_card_no_change：是正常决定/);assert.doesNotMatch(modificationSystem,/decisionToken|roleId|artifact SHA/);assert.match(modificationSystem,/纯文字 final 不算完成/);assert.match(modificationSystem,/Harness 可读的全文不等于原 Expert 的视野/);assert.match(modificationSystem,/Description 的全篇写作目标不能自动扩成当前局部单位的硬否决条件/);
  for(const forbidden of ['HISTORY_SENTINEL','案例 5','口语化 token','Revit','Fusion','Rhino']){assert.equal(diagnosisSystem.includes(forbidden),false);assert.equal(modificationSystem.includes(forbidden),false);}
  const capture=process.env.CARD_STAGE_SHADOW_CAPTURE;if(capture){await mkdir(capture,{recursive:true});await copyFile(diag.path,join(capture,'diagnosis-config.json'));await copyFile(frozen.path,join(capture,'diagnosis-receipt.json'));await copyFile(mod.path,join(capture,'modification-config.json'));await writeFile(join(capture,'payloads.json'),JSON.stringify(requests,null,2));await writeFile(join(capture,'proof.json'),JSON.stringify({kind:'local-loopback-infrastructure-proof-not-semantic-evidence',providerOrigin:origin,paidProviderRequests:0,expertRequests:0,trialRuns:0,diagnosisRequests:2,modificationRequests:2,inputBounds:requests.map(request=>Buffer.byteLength(JSON.stringify(request),'utf8')+4096),singleUserEveryRequest:requests.every(r=>r.messages.filter((m:any)=>m.role==='user').length===1),historicalSentinelAbsent:!serialized.includes('HISTORY_SENTINEL'),receiptDeliveredToModification:requests.some(r=>JSON.stringify(r).includes('S1 ORIGINAL')),authorizedParentOnly:requests.some(r=>JSON.stringify(r).includes('AUTHORIZED PARENT')),terminalStatus:modResult.terminalStatus},null,2));}}
 finally{server.closeAllConnections();await new Promise<void>(done=>server.close(()=>done()));}
});

test('separated preparation keeps unscoped legacy configs compatible and rejects unbound scoped updates',async()=>{
 const root=await mkdtemp(join(tmpdir(),'separated-accounting-')),copies=join(root,'copies-root'),out=join(root,'out'),receiptPath=join(root,'receipt.json'),source={roleId:ALIGNER_ROLE,systemPrompt:'SOURCE'};const store=createExpertCardCopyStore(join(copies,'copies'),source,async()=>{});const v0=await store.card({action:'create',roleId:ALIGNER_ROLE});const receipt={kind:'frozen-observation-receipt',epistemicStatus:'model-observation-not-gold'};await writeFile(receiptPath,JSON.stringify(receipt));const common:any={baseConfig:{runtime:{root:copies,source,storeOptions:{reviewedCopies:{}},evidence:{sessions:{},artifacts:{},defaultArtifacts:{}}},provider:'offline',model:'offline',maxOutputTokens:1000,thinking:'off',budgetRoot:root,budgetGuardPath:join(root,'guard.ts'),phase:'offline',providerOrigin:'http://127.0.0.1',maxRequests:1,providerExtension:join(root,'provider.ts'),bindings:[]},outputRoot:out,system:'SYSTEM',prompt:'PROMPT'};
 const legacy=prepareSeparatedModificationStage(common,{artifacts:{},receiptPath,receiptSha256:cardDigest(await readFile(receiptPath,'utf8')),parentVersion:'v0'}),legacyConfig=JSON.parse(await readFile(legacy.path,'utf8'));assert.equal(legacyConfig.expertExecution,undefined);assert.equal(legacyConfig.runtime.settledTrialEvidence,undefined);
 common.baseConfig.runtime.storeOptions.trialAuthorization={id:'scoped',allowedNewVersions:['v1'],originVersions:{v0:v0.digest},requireReadyForTrial:true};await assert.rejects(async()=>prepareSeparatedModificationStage(common,{artifacts:{},receiptPath,receiptSha256:cardDigest(await readFile(receiptPath,'utf8')),parentVersion:'v0'}),/requires bound expertExecution accounting evidence/);
});

test('separated no-change rejects wrong tokens, roleId, and legacy digest fields before writing a receipt',async()=>{
 const root=await mkdtemp(join(tmpdir(),'separated-decision-contract-')),copies=join(root,'copies-root'),out=join(root,'out'),receiptPath=join(root,'receipt.json'),source={roleId:ALIGNER_ROLE,systemPrompt:'SOURCE'};const store=createExpertCardCopyStore(join(copies,'copies'),source,async()=>{});await store.card({action:'create',roleId:ALIGNER_ROLE});const receipt={kind:'frozen-observation-receipt',epistemicStatus:'model-observation-not-gold'};await writeFile(receiptPath,JSON.stringify(receipt));const common:any={baseConfig:{runtime:{root:copies,source,storeOptions:{reviewedCopies:{}},evidence:{sessions:{},artifacts:{},defaultArtifacts:{}}},provider:'offline',model:'offline',maxOutputTokens:1000,thinking:'off',budgetRoot:root,budgetGuardPath:join(root,'guard.ts'),phase:'offline',providerOrigin:'http://127.0.0.1',maxRequests:1,providerExtension:join(root,'provider.ts'),bindings:[]},outputRoot:out,system:'SYSTEM',prompt:'PROMPT'};const prepared=prepareSeparatedModificationStage(common,{artifacts:{},receiptPath,receiptSha256:cardDigest(await readFile(receiptPath,'utf8')),parentVersion:'v0'}),config=JSON.parse(await readFile(prepared.path,'utf8')),token=separatedModificationDecisionToken(config.runtime.separatedModificationDecision);
 config.runtime.modificationToolContract='legacy';
 const invoke=async(name:string,args:any)=>{let cardTool:any;const pi={registerTool(definition:any){if(definition.name==='expert_card_copy')cardTool=definition;},on(){},setActiveTools(){}};const runtime=createCardReplayRuntime(config.runtime,async()=>{throw Error('forbidden');});registerCardReplayTools(pi,runtime,join(root,name,'engineering-stop.json'));return cardTool.execute('call',args);};
 await assert.rejects(invoke('wrong-token',{action:'no-change',decisionToken:'0'.repeat(64),reason:'Evidence does not support a change.'}),/token does not match/);
 await assert.rejects(invoke('role-id',{action:'no-change',decisionToken:token,reason:'Evidence does not support a change.',roleId:ALIGNER_ROLE}),/Invalid no-change decision fields/);
 await assert.rejects(invoke('legacy-digests',{action:'no-change',observationReceiptSha256:config.runtime.separatedModificationDecision.observationReceiptSha256,parentVersion:'v0',parentDigest:config.runtime.separatedModificationDecision.parentDigest,reason:'Evidence does not support a change.'}),/Invalid no-change decision fields/);
 for(const name of ['wrong-token','role-id','legacy-digests'])await assert.rejects(readFile(join(root,name,'modification-no-change-receipt.json'),'utf8'));
});
