import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,writeFile,readFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {runMultiCaseHarness,registerMultiCaseHarness,type MultiCaseOptions} from '../src/harness-multi-case.js';
import {ALIGNER_ROLE,MATCHER_ROLE} from '../src/expert-card-copy-store.js';
import {bundledProviderExtensionPath} from '../src/agent-task-runner.js';
import {pathToFileURL} from 'node:url';
import {mkdirSync} from 'node:fs';
import {pendingHumanQuestions,writeControlJson,workflowCost} from '../src/human-workflow-channel.js';
const cases=[{caseId:'alpha',role:'Aligner',roleId:ALIGNER_ROLE,direction:'recall',axis:'style',samples:[{id:'old',result:false,rationale:'fixture observation'}],scope:{evidences:[{id:'e1',location:'p1'}]},catalog:[{id:'e1',quote:'fixture line',location:'p1'}]},{caseId:'beta',role:'Matcher',roleId:MATCHER_ROLE,direction:'precision',axis:null,samples:[{id:'old2',result:{matched:false,targetAspectId:null},rationale:'fixture observation'}],scope:{targets:[]},catalog:[]}];
async function options(root:string):Promise<MultiCaseOptions>{return{outputRoot:join(root,'batch'),cases,materials:[{id:'task',scope:'task-description',text:'A local fixture task'}],parents:[{roleId:ALIGNER_ROLE,systemPrompt:'UNSEEN_ALIGNER_PARENT'},{roleId:MATCHER_ROLE,systemPrompt:'UNSEEN_MATCHER_PARENT'}],task:{cwd:root,provider:'deepseek',model:'deepseek-v4-flash',thinking:'off',maxOutputTokens:8000,timeoutMs:60000},providerExtensions:[bundledProviderExtensionPath()],guardExtensions:{review:[],boundary:[]}};}
test('default prepares only; role paths remain isolated and schemas stay compact',async()=>{
 const root=await mkdtemp(join(tmpdir(),'multi-prepare-')),o=await options(root);let calls=0;const result=await runMultiCaseHarness(o,false,async()=>{calls++;throw Error('not allowed');});assert.equal(result.status,'prepared');assert.equal(calls,0);const config=JSON.parse(await readFile(join(o.outputRoot,'config.json'),'utf8')),tools:any[]=[];registerMultiCaseHarness({registerTool:(t:any)=>tools.push(t),on(){},setActiveTools(){}},config);
 for(const t of tools.filter(t=>t.name.startsWith('append_')))assert.equal(Buffer.byteLength(JSON.stringify(t.parameters)),200);
 config.runtimes.matcher.root=config.runtimes.aligner.root;assert.throws(()=>registerMultiCaseHarness({},config),/Role path/);
});
test('actual SDK: one native review session, boundary, staged two blind receipts; no network',async()=>{
 const root=await mkdtemp(join(tmpdir(),'multi-sdk-')),o=await options(root),guard=join(root,'fake-guard.ts');
 await writeFile(guard,`import {writeFileSync} from 'node:fs';let count=0;export default function(pi){let boundary=false;pi.on('before_provider_request',(e,c)=>{if(c.signal?.aborted)return;boundary=!e.payload.tools?.length;writeFileSync(${JSON.stringify(root)}+'/'+(boundary?'boundary':'review')+'-'+(++count)+'.json',JSON.stringify(e.payload));});globalThis.fetch=async()=>{const call=(name,args,i=0)=>({index:i,id:'fake-'+count+'-'+i,type:'function',function:{name,arguments:JSON.stringify(args)}});let calls=[];if(!boundary){if(count===1)calls=[call('read_case',{caseId:'alpha'}),call('read_case',{caseId:'beta'},1)];else if(count===2)calls=[call('read_evidence',{caseId:'alpha',ids:['e1']})];else if(count===3)calls=[call('ask_boundary',{caseId:'alpha',case:'Local fixture',evidence:[{id:'e1',quote:'fixture line'}],question:'Which limits apply?'})];else if(count===4)calls=[call('finish_review',{review:'A local interface record'})];else if(count===5)calls=[call('append_aligner',{promptAppend:'A generic fixture principle',badCaseAppend:'Fixture input -> output'})];else if(count===6)calls=[call('append_matcher',{promptAppend:'A matcher fixture principle',badCaseAppend:'Matcher fixture input -> output'})];else throw Error('Unexpected extra provider request');}const chunk=(delta,finish_reason=null)=>({id:'local',object:'chat.completion.chunk',created:0,model:'deepseek-v4-flash',choices:[{index:0,delta,finish_reason}]});const chunks=[chunk({role:'assistant',...(boundary?{content:'A fallible local boundary answer'}:{content:'',tool_calls:calls})}),chunk({},boundary?'stop':'tool_calls'),{...chunk({}),choices:[],usage:{prompt_tokens:5,completion_tokens:5,total_tokens:10}}];return new Response(chunks.map(c=>'data: '+JSON.stringify(c)+'\\n\\n').join('')+'data: [DONE]\\n\\n',{headers:{'content-type':'text/event-stream'}});};}`);
 o.guardExtensions={review:[guard],boundary:[guard]};const old=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='local-fake-no-remote-key';try{const result=await runMultiCaseHarness(o,true);assert.equal(result.status,'candidates-saved');const payloads=await Promise.all((await readdir(root)).filter(p=>/^review-\d+\.json$/.test(p)).sort().map(async p=>JSON.parse(await readFile(join(root,p),'utf8'))));assert.equal(payloads.length,6);assert.equal(payloads[4].tools.length,2);assert.deepEqual(payloads[5].tools.map((t:any)=>t.function.name),['append_matcher']);assert(!JSON.stringify(payloads).includes('UNSEEN_'));assert(payloads[5].messages.length>payloads[4].messages.length);for(const role of ['aligner','matcher']){const receipt=JSON.parse(await readFile(join(o.outputRoot,'roles',role,'card-append-receipt.json'),'utf8'));assert(receipt.parentPromptPreserved);}}finally{if(old===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=old;}
});

test('actual SDK user tool waits, resumes in the same session, records review and boundary costs; no network',async()=>{
 const root=await mkdtemp(join(tmpdir(),'human-sdk-')),o=await options(root),control=join(root,'control'),extension=join(root,'human.ts'),guard=join(root,'fake.ts');mkdirSync(control);
 writeControlJson(join(control,'boundaries.json'),[{id:'initial',source:'user',text:'Initial user boundary'}]);
 await writeFile(extension,`import {registerHumanRuntime} from ${JSON.stringify(new URL('../src/human-workflow-channel.ts',import.meta.url).href)};export default sdk=>registerHumanRuntime(sdk,${JSON.stringify(control)});`);
 await writeFile(guard,`import {writeFileSync} from 'node:fs';let n=0,boundary=false;export default sdk=>{sdk.on('before_provider_request',(e,c)=>{if(c.signal?.aborted)return;boundary=!e.payload.tools?.length;writeFileSync(${JSON.stringify(root)}+'/'+(boundary?'boundary':'review')+'-'+(++n)+'.json',JSON.stringify(e.payload));});globalThis.fetch=async()=>{let calls=[];const call=(name,args)=>({index:0,id:'local-'+n,type:'function',function:{name,arguments:JSON.stringify(args)}});if(!boundary){const sequence=[['read_case',{caseId:'alpha'}],['read_case',{caseId:'beta'}],['read_evidence',{caseId:'alpha',ids:['e1']}],['ask_user',{caseId:'alpha',question:'Is version coverage required?'}],['ask_boundary',{caseId:'alpha',case:'Local fixture',evidence:[{id:'e1',quote:'fixture line'}],question:'Which limit applies?'}],['finish_review',{review:'User clarification was received in this session'}],['append_aligner',{promptAppend:'Fixture principle',badCaseAppend:'Fixture input -> output'}],['append_matcher',{promptAppend:'Fixture principle',badCaseAppend:'Fixture input -> output'}]];if(!sequence[n-1])throw Error('Unexpected call');calls=[call(...sequence[n-1])];}const chunk=(delta,finish_reason=null)=>({id:'local',object:'chat.completion.chunk',created:0,model:'deepseek-v4-flash',choices:[{index:0,delta,finish_reason}]});return new Response([chunk({role:'assistant',...(boundary?{content:'Local boundary answer'}:{tool_calls:calls})}),chunk({},boundary?'stop':'tool_calls'),{...chunk({}),choices:[],usage:{prompt_tokens:5,completion_tokens:5,total_tokens:10}}].map(c=>'data: '+JSON.stringify(c)+'\\n\\n').join('')+'data: [DONE]\\n\\n',{headers:{'content-type':'text/event-stream'}});};};`);
 o.humanControlDirectory=control;o.task.humanControlDirectory=control;o.providerExtensions.push(extension);o.guardExtensions={review:[guard],boundary:[guard]};
 let answered=false;const responder=setInterval(()=>{const question=pendingHumanQuestions(control)[0];if(!question||answered)return;answered=true;writeControlJson(join(control,'boundaries.json'),[{id:'new',source:'user',text:'Version coverage is not required'}]);writeControlJson(join(control,'answers',question.id+'.json'),{answer:'Do not require version coverage',source:'user'});},25);
 const old=process.env.DEEPSEEK_API_KEY;process.env.DEEPSEEK_API_KEY='local-fake-no-network';
 try {const result=await runMultiCaseHarness(o,true);assert.equal(result.status,'candidates-saved');assert(answered);const payload=await readFile(join(root,'review-5.json'),'utf8');assert.match(payload,/Do not require version coverage/);const boundary=await readFile(join(o.outputRoot,'boundary-alpha','input.txt'),'utf8');assert.match(boundary,/Version coverage is not required/);const costs=workflowCost([control]);assert.equal(costs.unsettledRequests,0);assert(costs.requests>=9);assert(costs.settledUsd>0);}finally{clearInterval(responder);if(old===undefined)delete process.env.DEEPSEEK_API_KEY;else process.env.DEEPSEEK_API_KEY=old;}
});
