export const PRODUCTION_RULES = {
  version: 2,
  sessionProjectionVersion: 1,
  intermediateDocumentFormat: "markdown",
  imageHandling: "placeholder-only",
  imagePlaceholder: "[图片留空]",
  acceptedArtifactExtensions: [".docx", ".pdf", ".md", ".markdown"] as const,
  preferredArtifactExtensions: [".docx", ".pdf", ".md", ".markdown"] as const,
  excludeHiddenReasoning: true,
  acontextTrainingMessages: "user-and-assistant-text-only",
  acontextGoldInjectionMode: "disabled-refine-reads-full-gold",
  learningFailureGracePeriodMs: 60_000,
  pipelineOnlySignals: [
    "[图片留空]",
    "图片占位",
    "文件中转",
    "交付 agent",
    "生产管线",
    "中间 markdown",
    "markdown 报告",
    "markdown 文档",
    "markdown 文件",
    "工具调用",
    "read 工具",
    "加载 skill",
    "subagent/并行安排",
  ] as const,
  pipelineDocumentWorkflowFormats: ["markdown", ".md", "docx"] as const,
  pipelineDocumentWorkflowVerbs: ["中间", "文件中转", "多轮修改", "修改与审阅", "审阅后", "供后续格式转换", "转成最终", "转换后交付"] as const,
  pipelineSkillWorkflowVerbs: ["加载", "注入", "同步", "由工具处理", "由生产管线处理"] as const,
  injectNormalizedGoldIntoLearning: false,
  requireFreshRunDirectory: true,
  forbidResumeFromPriorRun: true,
  requireReviewerReadEvidence: true,
  goldSelection: "last-generated-artifact",
  baselineSelection: "first-generated-artifact",
} as const;

export type ProductionRangeKind = "acontext" | "refine";
