import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { basename, resolve } from "node:path";
import type { AgentEventProvenance } from "./agent-task-runner.js";
import type { HarnessTraceStage } from "./refine-harness-self-check.js";

type FlatStage = HarnessTraceStage | NonNullable<HarnessTraceStage["subtasks"]>[number];
type TraceAttempt = NonNullable<FlatStage["attempts"]>[number];
type Counts = { records: number; bytes: number };
export interface TraceAuditOptions { allowLegacyMissingEventProvenance?: boolean }
export interface TraceIntegrityFinding {
  code: "TRACE_CONTROL_EVIDENCE_INVALID" | "GT-TRACE-001" | "TRACE_EVENTS_PATH_MISSING" | "TRACE_EVENTS_UNAVAILABLE" | "TRACE_EVENTS_PROVENANCE_MISSING" | "TRACE_EVENTS_PROVENANCE_MISMATCH" | "TRACE_ATTEMPT_IDENTITY_REUSED" | "TRACE_LIFECYCLE_INVALID" | "TRACE_IO_MISMATCH" | "TRACE_TOOL_PAIR_MISMATCH" | "TRACE_STATUS_MISMATCH" | "TRACE_ARTIFACT_INVALID" | "TRACE_PRIVATE_DATA_STORED" | "TRACE_SENSITIVE_DATA_STORED";
  invocationId: string; eventRef: string | null; message: string;
}
export interface PublicTraceEvidence { kind: "contract" | "assistant_intermediate" | "assistant_final" | "tool_call" | "tool_result"; eventRef: string; status: string | null; summary: string; sha256: string }
export interface TraceAgentConfiguration {
  ref: string; roleId: string | null; cardVersion: string | null; cardDigest: string | null; embeddedSkillDigest: string | null;
  promptDigest: string | null; schemaDigest: string | null; toolDigest: string | null; provider: string | null; model: string | null;
  toolAllowlist: readonly string[] | null; unavailable: string[];
}
export interface TraceOutputArtifactTerminal { file: string; sha256: string; terminalEventRef: string }
export interface ObservableTraceSummary {
  invocationId: string; stage: string; roleId: string | null; attempt: number; status: string; eventsPath: string | null; eventsSha256: string | null; records: number;
  eventTypeCounts: Record<string, number>; contractRefs: string[]; assistantRefs: string[]; toolCallRefs: string[]; toolResultRefs: string[]; contractDigests: string[]; contractPreviews: string[]; assistantFinalDigests: string[]; toolNames: string[]; stopReasons: string[]; terminalTypes: string[]; lifecycleRefs: Array<{ type: string; eventRef: string }>; usageRefs: Array<{ eventRef: string; input: number; output: number; cacheRead: number; cacheWrite: number; totalTokens: number; costUsd: number }>; errorObservation: { source: "manifest"; eventRef: null; message: string } | null; publicEvidence: PublicTraceEvidence[]; configuration: TraceAgentConfiguration; outputArtifactTerminals: TraceOutputArtifactTerminal[];
  usage: { input: number; output: number; cacheRead: number; cacheWrite: number; totalTokens: number; costUsd: number }; publicRecords: number; privateRecords: number; redactedRecords: number;
}
export interface TraceIntegrityMatrixRow extends ObservableTraceSummary { complete: boolean; inputObserved: boolean; outputObserved: boolean; toolPairsConsistent: boolean; terminalObserved: boolean; statusConsistent: boolean; parseFailures: number }
export interface RefineTraceIntegrityReport {
  schemaVersion: "1.1"; category: "refine_public_trace_integrity"; valid: boolean; privateReasoningPolicy: "not-read-not-stored"; completenessMatrix: TraceIntegrityMatrixRow[]; controlStops?: Array<{ invocationId: string; stage: string; attempt: number; reason: string; providerStarted: false; evidencePath: string; evidenceSha256: string; error: string | null }>; findings: TraceIntegrityFinding[];
  raw: { events: { files: number } & Counts; sourceEvents: Counts; artifacts: { declarations: number; files: number; bytes: number }; included: Counts; omitted: Counts; redacted: Counts; private: Counts; omittedPrivate: Counts; parseFailures: Counts };
}

const sha = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex");
const flatStages = (stages: readonly HarnessTraceStage[]): FlatStage[] => stages.flatMap((stage) => [stage, ...(stage.subtasks ?? [])]);
const isModelInvocation = (stage: FlatStage) => (!("kind" in stage) || stage.kind !== "deterministic-tool") && Boolean(stage.provider || stage.model || stage.card?.roleId);
const numeric = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : 0;
const eventRef = (digest: string, line: number) => `event:${digest.slice(0, 16)}:L${line}`;
const privateName = (value: unknown) => /thinking|reasoning|private|hidden/i.test(String(value ?? ""));
function redact(raw: string) { let value = raw; let redacted = false; const replace = (pattern: RegExp, replacement: string) => { const next = value.replace(pattern, replacement); redacted ||= next !== value; value = next; }; replace(/Bearer\s+[A-Za-z0-9._~+\/-]+=*/gi, "Bearer [REDACTED]"); replace(/\bsk-[A-Za-z0-9_-]{12,}\b/g, "[REDACTED_KEY]"); replace(/"(api[_-]?key|x-api-key|authorization|password|secret|token|access[_-]?token|refresh[_-]?token)"\s*:\s*"[^"]*"/gi, '"$1":"[REDACTED]"'); return { value, redacted }; }
function preview(raw: string, max = 180) { return [...redact(raw).value.replace(/\s+/g, " ").trim()].slice(0, max).join(""); }
function blocks(message: Record<string, unknown>) { return Array.isArray(message.content) ? message.content.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))) : []; }
function publicText(message: Record<string, unknown>) { return blocks(message).filter((block) => block.type === "text" && typeof block.text === "string").map((block) => block.text as string).join("\n"); }
function containsPrivate(event: Record<string, unknown>) { if (privateName(event.type) || Object.keys(event).some(privateName)) return true; const stream = event.assistantMessageEvent; if (stream && typeof stream === "object" && !Array.isArray(stream) && privateName((stream as Record<string, unknown>).type)) return true; const message = event.message; return Boolean(message && typeof message === "object" && !Array.isArray(message) && blocks(message as Record<string, unknown>).some((block) => privateName(block.type) || Object.keys(block).some(privateName))); }
function evidence(kind: PublicTraceEvidence["kind"], ref: string, raw: string, status: string | null = null): PublicTraceEvidence { const summary = preview(raw); return { kind, eventRef: ref, status, summary, sha256: sha(summary) }; }
function summarizeArgs(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return preview(String(value ?? "")); const object = value as Record<string, unknown>; const paths: Record<string, unknown> = {}; for (const key of ["path", "filePath", "file_path", "output_path"]) if (typeof object[key] === "string") paths[key] = object[key]; return preview(JSON.stringify(Object.keys(paths).length ? paths : object), 200); }
function summarizeResult(value: unknown) { if (typeof value === "string") return preview(value, 160); try { return preview(JSON.stringify(value), 160); } catch { return "[unserializable public result]"; } }
function configuration(stage: FlatStage): TraceAgentConfiguration {
  const value = { roleId: stage.card?.roleId ?? null, cardVersion: stage.card?.version ?? null, cardDigest: stage.card?.digest ?? null,
    embeddedSkillDigest: stage.card?.embeddedSkill === undefined ? null : sha(JSON.stringify(stage.card.embeddedSkill)), promptDigest: stage.card?.promptDigest ?? null,
    schemaDigest: stage.card?.schemaDigest ?? null, toolDigest: stage.card?.toolDigest ?? null, provider: stage.provider ?? null, model: stage.model ?? null,
    toolAllowlist: stage.toolAllowlist === undefined ? null : [...stage.toolAllowlist] };
  const unavailable = Object.entries(value).filter(([, item]) => item === null).map(([key]) => key);
  return { ref: `config:${sha(JSON.stringify(value)).slice(0, 16)}`, ...value, unavailable };
}
function missingRow(stage: FlatStage, attempt: Pick<TraceAttempt, "attempt" | "taskId" | "status">, path: string | null): TraceIntegrityMatrixRow { return { invocationId: attempt.taskId, stage: stage.stage, roleId: stage.card?.roleId ?? null, attempt: attempt.attempt, status: attempt.status, eventsPath: path, eventsSha256: null, records: 0, eventTypeCounts: {}, contractRefs: [], assistantRefs: [], toolCallRefs: [], toolResultRefs: [], contractDigests: [], contractPreviews: [], assistantFinalDigests: [], toolNames: [], stopReasons: [], terminalTypes: [], lifecycleRefs: [], usageRefs: [], errorObservation: null, publicEvidence: [], configuration: configuration(stage), outputArtifactTerminals: [], usage: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, costUsd: 0 }, publicRecords: 0, privateRecords: 0, redactedRecords: 0, complete: false, inputObserved: false, outputObserved: false, toolPairsConsistent: false, terminalObserved: false, statusConsistent: false, parseFailures: 0 }; }
function provenanceMatches(value: AgentEventProvenance, digest: string, bytes: number, records: number) { return value.format === "public-jsonl" && value.sha256 === digest && value.bytes === bytes && value.records === records && value.sourceRecords >= records && value.sourceBytes >= bytes; }

async function authenticateControlStop(stage: FlatStage, attempt: TraceAttempt & { usage?: Record<string, number>; readPaths?: string[] }) {
  const control = (attempt as TraceAttempt & { controlStop?: { reason: string; providerStarted: boolean; evidencePath?: string; evidenceSha256?: string } }).controlStop;
  if (!control) return null;
  if (control.providerStarted !== false || attempt.status !== "failed" || !control.evidencePath || !control.evidenceSha256) throw new Error("Control stop lacks authenticated pre-provider evidence");
  const text = await readFile(control.evidencePath, "utf8");
  if (sha(text) !== control.evidenceSha256) throw new Error("Control proof digest mismatch");
  const proof = JSON.parse(text); const key = (path: string) => resolve(path).toLowerCase();
  if (typeof proof.runId !== "string" || !attempt.taskId.startsWith(`${proof.runId}:`) || proof.preProviderGuardVerified !== true || !Array.isArray(proof.unsentAttempts) || !proof.unsentAttempts.some((item: { stage: string; attempt: number; eventsPath: string }) => item.stage === stage.stage && item.attempt === attempt.attempt && key(item.eventsPath) === key(attempt.eventsPath!))) throw new Error("Control proof does not identify this attempt");
  const ledger = await readFile(proof.ledgerPath, "utf8");
  if (sha(ledger) !== proof.ledgerSha256) throw new Error("Control proof ledger digest mismatch; use an immutable audited ledger snapshot");
  if (ledger.split(/\r?\n/).filter(Boolean).map(line => JSON.parse(line)).some(row => row.taskId === attempt.taskId || typeof row.eventsPath === "string" && key(row.eventsPath) === key(attempt.eventsPath!))) throw new Error("Control attempt appears in provider ledger");
  if (attempt.usage && Object.values(attempt.usage).some(value => value !== 0) || attempt.eventProvenance || attempt.readPaths?.length) throw new Error("Control attempt has execution metadata");
  const bytes = attempt.eventsPath ? await readFile(attempt.eventsPath).catch((error: NodeJS.ErrnoException) => { if (error.code === "ENOENT") return Buffer.alloc(0); throw error; }) : Buffer.alloc(0);
  if (bytes.length) throw new Error("Control attempt has public event bytes");
  return { invocationId: attempt.taskId, stage: stage.stage, attempt: attempt.attempt, reason: control.reason, providerStarted: false as const, evidencePath: control.evidencePath, evidenceSha256: control.evidenceSha256, error: attempt.error ?? null };
}

export async function auditRefineTraceIntegrity(stages: readonly HarnessTraceStage[], options: TraceAuditOptions = {}): Promise<RefineTraceIntegrityReport> {
  const findings: TraceIntegrityFinding[] = []; const matrix: TraceIntegrityMatrixRow[] = []; const controlStops: NonNullable<RefineTraceIntegrityReport["controlStops"]> = [];
  const raw = { events: { files: 0, records: 0, bytes: 0 }, sourceEvents: { records: 0, bytes: 0 }, artifacts: { declarations: 0, files: 0, bytes: 0 }, included: { records: 0, bytes: 0 }, omitted: { records: 0, bytes: 0 }, redacted: { records: 0, bytes: 0 }, private: { records: 0, bytes: 0 }, omittedPrivate: { records: 0, bytes: 0 }, parseFailures: { records: 0, bytes: 0 } };
  const eventFiles = new Map<string, Counts>(); const artifactPaths = new Set<string>(); const artifactCache = new Map<string, { bytes: number; digest: string } | null>(); const artifactFindingKeys = new Set<string>(); const seenIds = new Map<string, string>(); const seenPaths = new Map<string, string>();
  for (const stage of flatStages(stages)) for (const artifact of [...(stage.inputArtifacts ?? []), ...(stage.outputArtifacts ?? [])]) { raw.artifacts.declarations += 1; const path = resolve(artifact.path).toLowerCase(); if (!artifactCache.has(path)) { try { const bytes = await readFile(artifact.path); artifactCache.set(path, { bytes: bytes.length, digest: sha(bytes) }); raw.artifacts.bytes += bytes.length; } catch { artifactCache.set(path, null); } } artifactPaths.add(path); const actual = artifactCache.get(path); const reason = actual ? actual.digest === artifact.sha256 ? null : "digest mismatch" : "unavailable"; const key = `${stage.taskId}\0${path}\0${reason}`; if (reason && !artifactFindingKeys.has(key)) { artifactFindingKeys.add(key); findings.push({ code: "TRACE_ARTIFACT_INVALID", invocationId: stage.taskId, eventRef: null, message: `Artifact ${reason}: ${basename(artifact.path)}` }); } }
  raw.artifacts.files = artifactPaths.size;
  for (const [stageIndex, stage] of flatStages(stages).filter(isModelInvocation).entries()) {
    if (!stage.eventsPath) findings.push({ code: "TRACE_EVENTS_PATH_MISSING", invocationId: stage.taskId, eventRef: null, message: `Model invocation ${stage.stage} has no final eventsPath` });
    const declaredStageStatus = "status" in stage ? stage.status : undefined;
    const attempts: TraceAttempt[] = stage.attempts?.length ? [...stage.attempts] : [{ attempt: 1, taskId: stage.taskId, ...(stage.eventsPath ? { eventsPath: stage.eventsPath } : {}), status: String(declaredStageStatus ?? "completed"), ...(stage.eventProvenance ? { eventProvenance: stage.eventProvenance } : {}) }];
    const terminal = attempts.at(-1); const numbers = attempts.map((item) => item.attempt); if (new Set(numbers).size !== numbers.length || numbers.some((number, index) => !Number.isInteger(number) || number < 1 || (index > 0 && number <= numbers[index - 1]!))) findings.push({ code: "TRACE_STATUS_MISMATCH", invocationId: stage.taskId, eventRef: null, message: "Attempt sequence must be unique and strictly increasing" });
    if (stage.eventsPath && terminal?.eventsPath && resolve(stage.eventsPath).toLowerCase() !== resolve(terminal.eventsPath).toLowerCase()) findings.push({ code: "TRACE_STATUS_MISMATCH", invocationId: stage.taskId, eventRef: null, message: "Invocation eventsPath does not point to its terminal attempt" });
    const stageStatus = String(declaredStageStatus ?? terminal?.status ?? "completed"); if (terminal && !(((stageStatus === "completed" || stageStatus === "recovered") && terminal.status === "completed") || (stageStatus === "failed" && terminal.status === "failed"))) findings.push({ code: "TRACE_STATUS_MISMATCH", invocationId: stage.taskId, eventRef: null, message: `Stage status ${stageStatus} disagrees with terminal attempt ${terminal.status}` });
    for (const attempt of attempts) {
      const invocationId = attempt.taskId || `${stage.taskId}:attempt-${attempt.attempt}`; const identity = `${stageIndex}:${stage.stage}:${stage.taskId}:attempt-${attempt.attempt}`; const path = attempt.eventsPath;
      const priorId = seenIds.get(invocationId); if (priorId && priorId !== identity) findings.push({ code: "TRACE_ATTEMPT_IDENTITY_REUSED", invocationId, eventRef: null, message: `Attempt taskId is already bound to ${priorId}` }); else seenIds.set(invocationId, identity);
      if (path) { const resolved = resolve(path).toLowerCase(); const priorPath = seenPaths.get(resolved); if (priorPath && priorPath !== identity) findings.push({ code: "TRACE_ATTEMPT_IDENTITY_REUSED", invocationId, eventRef: null, message: `Events path is already bound to ${priorPath}` }); else seenPaths.set(resolved, identity); }
      try { const control = await authenticateControlStop(stage, attempt); if (control) { controlStops.push(control); continue; } }
      catch (error) { findings.push({ code: "TRACE_CONTROL_EVIDENCE_INVALID", invocationId, eventRef: null, message: error instanceof Error ? error.message : String(error) }); matrix.push(missingRow(stage, attempt, path ?? null)); continue; }
      if (!path) { findings.push({ code: "TRACE_EVENTS_PATH_MISSING", invocationId, eventRef: null, message: `Model attempt ${stage.stage} has no eventsPath` }); matrix.push(missingRow(stage, attempt, null)); continue; }
      let bytes: Buffer; try { bytes = await readFile(path); } catch { findings.push({ code: "TRACE_EVENTS_UNAVAILABLE", invocationId, eventRef: null, message: `Events unavailable: ${path}` }); matrix.push(missingRow(stage, attempt, path)); continue; }
      const digest = sha(bytes); const lines = bytes.toString("utf8").split(/\r?\n/); const typeCounts: Record<string, number> = {}; const contractRefs: string[] = []; const assistantRefs: string[] = []; const toolCallRefs: string[] = []; const toolResultRefs: string[] = []; const contractDigests: string[] = []; const contractPreviews: string[] = []; const assistantFinalDigests: string[] = []; const publicEvidence: PublicTraceEvidence[] = []; const assistantObservations: Array<{ ref: string; text: string; stopReason: string }> = []; let terminalAssistantEvidence: PublicTraceEvidence | null = null; const toolNames = new Set<string>(); const stopReasons: string[] = []; const terminalTypes = new Set<string>(); const lifecycleRefs: Array<{ type: string; eventRef: string }> = []; const usageRefs: ObservableTraceSummary["usageRefs"] = []; const calls = new Map<string, string>(); const results = new Set<string>(); const usage = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, totalTokens: 0, costUsd: 0 }; let records = 0; let parseFailures = 0; let publicRecords = 0; let privateRecords = 0; let redactedRecords = 0; let inputObserved = false; let outputObserved = false;
      for (let index = 0; index < lines.length; index += 1) {
        const line = lines[index]!; if (!line.trim()) continue; records += 1; const lineBytes = Buffer.byteLength(line) + 1; let event: unknown;
        try { event = JSON.parse(line); } catch (error) { parseFailures += 1; raw.parseFailures.records += 1; raw.parseFailures.bytes += lineBytes; findings.push({ code: "GT-TRACE-001", invocationId, eventRef: eventRef(digest, index + 1), message: `Malformed JSONL record at line ${index + 1}: ${error instanceof Error ? error.message : String(error)}` }); continue; }
        if (!event || typeof event !== "object" || Array.isArray(event)) { raw.omitted.records += 1; raw.omitted.bytes += lineBytes; continue; }
        const object = event as Record<string, unknown>; const type = String(object.type ?? "unknown"); typeCounts[type] = (typeCounts[type] ?? 0) + 1; const ref = eventRef(digest, index + 1); if (["agent_start", "turn_start", "turn_end", "agent_end", "agent_settled"].includes(type)) { lifecycleRefs.push({ type, eventRef: ref }); if (["agent_end", "agent_settled", "turn_end"].includes(type)) terminalTypes.add(type); }
        if (containsPrivate(object)) { privateRecords += 1; raw.private.records += 1; raw.private.bytes += lineBytes; findings.push({ code: "TRACE_PRIVATE_DATA_STORED", invocationId, eventRef: ref, message: "Persisted events contain hidden/private reasoning data" }); continue; }
        let included = false;
        if (type === "message_end" && object.message && typeof object.message === "object" && !Array.isArray(object.message)) {
          const message = object.message as Record<string, unknown>; const role = String(message.role ?? ""); const text = publicText(message);
          if (role === "user" && text.trim()) { const safe = redact(text).value; inputObserved = true; contractRefs.push(ref); contractDigests.push(sha(safe)); contractPreviews.push(preview(safe)); publicEvidence.push(evidence("contract", ref, safe)); included = true; }
          if (role === "assistant") { const stopReason = typeof message.stopReason === "string" ? message.stopReason : ""; if (stopReason) stopReasons.push(stopReason); for (const block of blocks(message)) if (block.type === "toolCall" && typeof block.id === "string") { const name = String(block.name ?? "unknown"); calls.set(block.id, name); toolNames.add(name); toolCallRefs.push(ref); publicEvidence.push(evidence("tool_call", ref, `${name} ${summarizeArgs(block.arguments)}`, "requested")); included = true; } if (text.trim()) { const safe = redact(text).value; assistantRefs.push(ref); assistantObservations.push({ ref, text: safe, stopReason }); included = true; } if (message.usage && typeof message.usage === "object" && !Array.isArray(message.usage)) { const observed = message.usage as Record<string, unknown>; const observedUsage = { eventRef: ref, input: numeric(observed.input), output: numeric(observed.output), cacheRead: numeric(observed.cacheRead), cacheWrite: numeric(observed.cacheWrite), totalTokens: numeric(observed.totalTokens), costUsd: observed.cost && typeof observed.cost === "object" ? numeric((observed.cost as Record<string, unknown>).total) : 0 }; usageRefs.push(observedUsage); usage.input += observedUsage.input; usage.output += observedUsage.output; usage.cacheRead += observedUsage.cacheRead; usage.cacheWrite += observedUsage.cacheWrite; usage.totalTokens += observedUsage.totalTokens; usage.costUsd += observedUsage.costUsd; included = true; } }
          if (role === "toolResult" && typeof message.toolCallId === "string") { results.add(message.toolCallId); toolResultRefs.push(ref); publicEvidence.push(evidence("tool_result", ref, summarizeResult(message.content), message.isError === true ? "error" : "completed")); included = true; }
        }
        if (type === "tool_execution_start" && typeof object.toolCallId === "string") { const name = String(object.toolName ?? "unknown"); calls.set(object.toolCallId, name); toolNames.add(name); toolCallRefs.push(ref); publicEvidence.push(evidence("tool_call", ref, `${name} ${summarizeArgs(object.args ?? object.arguments)}`, "started")); included = true; }
        if (type === "tool_execution_end" && typeof object.toolCallId === "string") { results.add(object.toolCallId); toolResultRefs.push(ref); publicEvidence.push(evidence("tool_result", ref, summarizeResult(object.result), object.isError === true ? "error" : "completed")); included = true; }
        if (["agent_end", "agent_settled", "turn_end"].includes(type)) included = true; const sanitized = redact(line); if (sanitized.redacted) { redactedRecords += 1; raw.redacted.records += 1; raw.redacted.bytes += lineBytes; findings.push({ code: "TRACE_SENSITIVE_DATA_STORED", invocationId, eventRef: ref, message: "Persisted public events contain an unredacted credential-like value" }); } if (included) { publicRecords += 1; raw.included.records += 1; raw.included.bytes += Buffer.byteLength(sanitized.value); } else { raw.omitted.records += 1; raw.omitted.bytes += lineBytes; }
      }
      const terminalObservation = assistantObservations.filter((item) => item.stopReason && item.stopReason !== "toolUse" && item.stopReason !== "pending").at(-1); for (const item of assistantObservations) { const selectedTerminal = item === terminalObservation; const projected = evidence(selectedTerminal ? "assistant_final" : "assistant_intermediate", item.ref, item.text, item.stopReason || null); publicEvidence.push(projected); if (selectedTerminal) terminalAssistantEvidence = projected; } if (terminalAssistantEvidence) { assistantFinalDigests.push(terminalAssistantEvidence.sha256); outputObserved = true; }
      publicEvidence.sort((left, right) => Number(/:L(\d+)$/.exec(left.eventRef)?.[1] ?? 0) - Number(/:L(\d+)$/.exec(right.eventRef)?.[1] ?? 0));
      const resolved = resolve(path).toLowerCase(); if (!eventFiles.has(resolved)) { eventFiles.set(resolved, { bytes: bytes.length, records }); raw.events.bytes += bytes.length; raw.events.records += records; }
      const declared = attempt.eventProvenance; if (!declared && !options.allowLegacyMissingEventProvenance) findings.push({ code: "TRACE_EVENTS_PROVENANCE_MISSING", invocationId, eventRef: null, message: "Current formal audit requires per-attempt public event provenance" }); if (declared) { if (!provenanceMatches(declared, digest, bytes.length, records)) findings.push({ code: "TRACE_EVENTS_PROVENANCE_MISMATCH", invocationId, eventRef: null, message: `Declared event provenance disagrees with ${basename(path)}` }); raw.sourceEvents.records += declared.sourceRecords; raw.sourceEvents.bytes += declared.sourceBytes; raw.omittedPrivate.records += declared.omittedPrivate.records; raw.omittedPrivate.bytes += declared.omittedPrivate.bytes; raw.redacted.records += declared.redacted.records; raw.redacted.bytes += declared.redacted.bytes; } else { raw.sourceEvents.records += records; raw.sourceEvents.bytes += bytes.length; }
      const callIds = [...calls.keys()]; const toolPairsConsistent = callIds.every((id) => results.has(id)) && [...results].every((id) => calls.has(id)); const terminalObserved = (typeCounts.agent_start ?? 0) === 1 && (typeCounts.agent_end ?? 0) === 1 && (typeCounts.agent_settled ?? 0) === 1 && (typeCounts.turn_start ?? 0) >= 1 && typeCounts.turn_start === typeCounts.turn_end; const hasExplicitError = typeof attempt.error === "string" && Boolean(attempt.error.trim()); const failedWithoutFinal = attempt.status === "failed" && hasExplicitError && !outputObserved; const statusConsistent = attempt.status === "completed" ? terminalObserved && outputObserved : attempt.status === "failed" ? terminalObserved && hasExplicitError : false;
      if (!inputObserved || (attempt.status === "completed" && !outputObserved) || (attempt.status === "failed" && !outputObserved && !failedWithoutFinal)) findings.push({ code: "TRACE_IO_MISMATCH", invocationId, eventRef: null, message: `Public input/final semantics invalid: input=${inputObserved} output=${outputObserved} status=${attempt.status} explicitError=${Boolean(attempt.error?.trim())}` }); if (!toolPairsConsistent) findings.push({ code: "TRACE_TOOL_PAIR_MISMATCH", invocationId, eventRef: null, message: `Tool calls/results do not pair: calls=${callIds.length} results=${results.size}` }); if (!terminalObserved) findings.push({ code: "TRACE_LIFECYCLE_INVALID", invocationId, eventRef: null, message: `Lifecycle counts are inconsistent: start=${typeCounts.agent_start ?? 0} end=${typeCounts.agent_end ?? 0} settled=${typeCounts.agent_settled ?? 0} turns=${typeCounts.turn_start ?? 0}/${typeCounts.turn_end ?? 0}` }); if (!statusConsistent) findings.push({ code: "TRACE_STATUS_MISMATCH", invocationId, eventRef: null, message: `Manifest status ${attempt.status} disagrees with observable terminal/final/error state` });
      const provenanceValid = Boolean(declared ? provenanceMatches(declared, digest, bytes.length, records) : options.allowLegacyMissingEventProvenance); const complete = parseFailures === 0 && privateRecords === 0 && inputObserved && (outputObserved || failedWithoutFinal) && toolPairsConsistent && terminalObserved && statusConsistent && provenanceValid; const uniqueEvidence = [...new Map(publicEvidence.map((item) => [`${item.kind}\0${item.eventRef}\0${item.summary}`, item])).values()];
      const outputArtifactTerminals = attempt === terminal && attempt.status === "completed" && terminalAssistantEvidence ? (stage.outputArtifacts ?? []).map((artifact) => ({ file: basename(artifact.path), sha256: artifact.sha256, terminalEventRef: terminalAssistantEvidence!.eventRef })) : [];
      const errorObservation = typeof attempt.error === "string" && attempt.error.trim() ? { source: "manifest" as const, eventRef: null, message: preview(attempt.error, 240) } : null;
      matrix.push({ invocationId, stage: stage.stage, roleId: stage.card?.roleId ?? null, attempt: attempt.attempt, status: attempt.status, eventsPath: path, eventsSha256: digest, records, eventTypeCounts: typeCounts, contractRefs, assistantRefs, toolCallRefs: [...new Set(toolCallRefs)], toolResultRefs: [...new Set(toolResultRefs)], contractDigests: [...new Set(contractDigests)], contractPreviews: [...new Set(contractPreviews)], assistantFinalDigests: [...new Set(assistantFinalDigests)], toolNames: [...toolNames], stopReasons, terminalTypes: [...terminalTypes], lifecycleRefs, usageRefs, errorObservation, publicEvidence: uniqueEvidence, configuration: configuration(stage), outputArtifactTerminals, usage, publicRecords, privateRecords, redactedRecords, complete, inputObserved, outputObserved, toolPairsConsistent, terminalObserved, statusConsistent, parseFailures });
    }
  }
  raw.events.files = eventFiles.size; return { schemaVersion: "1.1", category: "refine_public_trace_integrity", valid: findings.length === 0 && matrix.length > 0 && matrix.every((row) => row.complete), privateReasoningPolicy: "not-read-not-stored", completenessMatrix: matrix, controlStops, findings, raw };
}
export function assertRefineTraceIntegrity(report: RefineTraceIntegrityReport): void { if (!report.valid) { const codes = [...new Set(report.findings.map((finding) => finding.code))].join(",") || "empty-matrix"; throw new Error(`Refine observable Trace integrity failed (${codes}); behavior compression and model invocation refused`); } }
